#!/usr/bin/env bash

# This bash script deploys the application.

# Entire script should exit if any single line fails.
set -e

function cleanup_at_exit {
  git checkout master

  git branch -D deploy
}
trap cleanup_at_exit EXIT

# checks out a new branch called "deploy"
# needs to match the name of the branch
git checkout -b deploy

# webpack will run in "production mode"
webpack -p

# "force" add the otherwise gitignored build files
git add -f public/bundle.js public/bundle.js.map

# create a commit, even if nothing changed
git commit --allow-empty -m 'Deploying'

# push local "deploy" branch to the "master" branch on heroku
git push --force heroku deploy:master
